# Generated by Django 2.2.6 on 2019-10-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighboor', '0003_business'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='neighborhood',
            table='Neighborhood',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
