# Generated by Django 2.2.6 on 2019-10-28 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighboor', '0008_auto_20191028_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood', to=settings.AUTH_USER_MODEL),
        ),
    ]
