# Generated by Django 2.2.6 on 2019-10-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighboor', '0012_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='health_department_contact',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police_authority_contact',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
