# Generated by Django 2.2.6 on 2019-10-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighboor', '0013_auto_20191029_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='health_department_contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police_authority_contact',
            field=models.CharField(max_length=255),
        ),
    ]
