# Generated by Django 2.2.6 on 2019-10-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighboor', '0014_auto_20191029_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
