# Generated by Django 2.2.6 on 2019-10-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighboor', '0015_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
