# Generated by Django 2.2.6 on 2019-10-30 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighboor', '0021_auto_20191030_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood', to=settings.AUTH_USER_MODEL),
        ),
    ]
